force-app/main/default/objects/Account/fields/avatar_url__c.field-meta.xml
<CustomField>
    <fullName>avatar_url__c</fullName>
    <description>Avatar Image URL</description>
    <inlineHelpText>Avatar Image URL</inlineHelpText>
    <label>Avatar URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/HitHorizonsID__c.field-meta.xml
<CustomField>
    <fullName>HitHorizonsID__c</fullName>
    <description>HitHorizons ID</description>
    <label>HitHorizons ID</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LinkedIn__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn__c</fullName>
    <description>LinkedIn Profile URL</description>
    <inlineHelpText>LinkedIn Profile URL</inlineHelpText>
    <label>LinkedIn</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/CustomFieldMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Map custom fields to standard object fields used by PipeLaunch. Example: Your org uses a custom field name to specify an Account Annual Revenue</description>
    <label>PipeLaunch Custom Field Mapping</label>
</CustomObject>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Account_Annual_Revenue__c</fullName>
    <defaultValue>&quot;AnnualRevenue&quot;</defaultValue>
    <label>Account Annual Revenue</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_Avatar_URL__c.field-meta.xml
<CustomField>
    <fullName>Account_Avatar_URL__c</fullName>
    <defaultValue>&quot;avatar_url__c&quot;</defaultValue>
    <label>Account Avatar URL</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Account_Billing_City__c</fullName>
    <defaultValue>&quot;BillingCity&quot;</defaultValue>
    <label>Account Billing City</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Account_Billing_Country__c</fullName>
    <defaultValue>&quot;BillingCountry&quot;</defaultValue>
    <label>Account Billing Country</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_Billing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Billing_Country_Code__c</fullName>
    <defaultValue>&quot;BillingCountryCode&quot;</defaultValue>
    <label>Account Billing Country Code</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Account_Billing_State__c</fullName>
    <defaultValue>&quot;BillingState&quot;</defaultValue>
    <label>Account Billing State</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Account_Billing_Street__c</fullName>
    <defaultValue>&quot;BillingStreet&quot;</defaultValue>
    <label>Account Billing Street</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Brand_Name__c</fullName>
    <defaultValue>&quot;BrandName__c&quot;</defaultValue>
    <label>Account Brand Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_Description__c.field-meta.xml
<CustomField>
    <fullName>Account_Description__c</fullName>
    <defaultValue>&quot;Description&quot;</defaultValue>
    <label>Account Description</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_DunsNumber__c.field-meta.xml
<CustomField>
    <fullName>Account_DunsNumber__c</fullName>
    <defaultValue>&quot;DunsNumber__c&quot;</defaultValue>
    <label>Account D-U-N-S Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_HitHorizons_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_HitHorizons_ID__c</fullName>
    <defaultValue>&quot;HitHorizonsID__c&quot;</defaultValue>
    <label>Account HitHorizons ID</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_Industry__c.field-meta.xml
<CustomField>
    <fullName>Account_Industry__c</fullName>
    <defaultValue>&quot;Industry&quot;</defaultValue>
    <label>Account Industry</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_LinkedIn__c.field-meta.xml
<CustomField>
    <fullName>Account_LinkedIn__c</fullName>
    <defaultValue>&quot;LinkedIn__c&quot;</defaultValue>
    <label>Account LinkedIn</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_Number_Of_Employees__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Of_Employees__c</fullName>
    <defaultValue>&quot;NumberOfEmployees&quot;</defaultValue>
    <label>Account Number Of Employees</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_Phone__c.field-meta.xml
<CustomField>
    <fullName>Account_Phone__c</fullName>
    <defaultValue>&quot;Phone&quot;</defaultValue>
    <label>Account Phone</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Postal_Code__c</fullName>
    <defaultValue>&quot;BillingPostalCode&quot;</defaultValue>
    <label>Account Postal Code</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_SIC__c.field-meta.xml
<CustomField>
    <fullName>Account_SIC__c</fullName>
    <defaultValue>&quot;Sic&quot;</defaultValue>
    <label>Account SIC</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_Website__c.field-meta.xml
<CustomField>
    <fullName>Account_Website__c</fullName>
    <defaultValue>&quot;Website&quot;</defaultValue>
    <label>Account Website</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Account_YearStarted__c.field-meta.xml
<CustomField>
    <fullName>Account_YearStarted__c</fullName>
    <defaultValue>&quot;YearStarted&quot;</defaultValue>
    <label>Account YearStarted</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Company_Avatar_URL__c.field-meta.xml
<CustomField>
    <fullName>Company_Avatar_URL__c</fullName>
    <defaultValue>&quot;Company_Avatar_URL__c&quot;</defaultValue>
    <label>Company Avatar URL</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Company_LinkedIn__c.field-meta.xml
<CustomField>
    <fullName>Company_LinkedIn__c</fullName>
    <defaultValue>&quot;Company_LinkedIn__c&quot;</defaultValue>
    <label>Company LinkedIn</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Lead_Annual_Revenue__c</fullName>
    <defaultValue>&quot;AnnualRevenue&quot;</defaultValue>
    <label>Lead Annual Revenue</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_Avatar_URL__c.field-meta.xml
<CustomField>
    <fullName>Lead_Avatar_URL__c</fullName>
    <defaultValue>&quot;avatar_url__c&quot;</defaultValue>
    <label>Lead Avatar URL</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Lead_Billing_State__c</fullName>
    <defaultValue>&quot;State&quot;</defaultValue>
    <label>Lead Billing State</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Lead_Billing_Street__c</fullName>
    <defaultValue>&quot;Street&quot;</defaultValue>
    <label>Lead Billing Street</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Brand_Name__c</fullName>
    <defaultValue>&quot;BrandName__c&quot;</defaultValue>
    <label>Lead Brand Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_City__c.field-meta.xml
<CustomField>
    <fullName>Lead_City__c</fullName>
    <defaultValue>&quot;City&quot;</defaultValue>
    <label>Lead City</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_Country__c.field-meta.xml
<CustomField>
    <fullName>Lead_Country__c</fullName>
    <defaultValue>&quot;Country&quot;</defaultValue>
    <label>Lead Country</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Lead_Country_Code__c</fullName>
    <defaultValue>&quot;CountryCode&quot;</defaultValue>
    <label>Lead Country Code</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_Description__c.field-meta.xml
<CustomField>
    <fullName>Lead_Description__c</fullName>
    <defaultValue>&quot;Description&quot;</defaultValue>
    <label>Lead Description</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_DunsNumber__c.field-meta.xml
<CustomField>
    <fullName>Lead_DunsNumber__c</fullName>
    <defaultValue>&quot;CompanyDunsNumber__c&quot;</defaultValue>
    <label>Lead D-U-N-S Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_Industry__c.field-meta.xml
<CustomField>
    <fullName>Lead_Industry__c</fullName>
    <defaultValue>&quot;Industry&quot;</defaultValue>
    <label>Lead Industry</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_LinkedIn__c.field-meta.xml
<CustomField>
    <fullName>Lead_LinkedIn__c</fullName>
    <defaultValue>&quot;LinkedIn__c&quot;</defaultValue>
    <label>Lead LinkedIn</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_Number_Of_Employees__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number_Of_Employees__c</fullName>
    <defaultValue>&quot;NumberOfEmployees&quot;</defaultValue>
    <label>Lead Number Of Employees</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_Phone__c.field-meta.xml
<CustomField>
    <fullName>Lead_Phone__c</fullName>
    <defaultValue>&quot;Phone&quot;</defaultValue>
    <label>Lead Phone</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Lead_Postal_Code__c</fullName>
    <defaultValue>&quot;PostalCode&quot;</defaultValue>
    <label>Lead Postal Code</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_Salutation__c.field-meta.xml
<CustomField>
    <fullName>Lead_Salutation__c</fullName>
    <defaultValue>&quot;Salutation&quot;</defaultValue>
    <label>Lead Salutation</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_SIC__c.field-meta.xml
<CustomField>
    <fullName>Lead_SIC__c</fullName>
    <defaultValue>&quot;Sic__c&quot;</defaultValue>
    <label>Lead SIC</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_Title__c.field-meta.xml
<CustomField>
    <fullName>Lead_Title__c</fullName>
    <defaultValue>&quot;Title&quot;</defaultValue>
    <label>Lead Title</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_Website__c.field-meta.xml
<CustomField>
    <fullName>Lead_Website__c</fullName>
    <defaultValue>&quot;Website&quot;</defaultValue>
    <label>Lead Website</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_Xing__c.field-meta.xml
<CustomField>
    <fullName>Lead_Xing__c</fullName>
    <defaultValue>&quot;Xing__c&quot;</defaultValue>
    <label>Lead Xing</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomFieldMapping__c/fields/Lead_YearStarted__c.field-meta.xml
<CustomField>
    <fullName>Lead_YearStarted__c</fullName>
    <defaultValue>&quot;YearStarted__c&quot;</defaultValue>
    <label>Lead YearStarted</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <description>Use the identify the correct Company/Account name</description>
    <inlineHelpText>Use the identify the correct Company/Account name</inlineHelpText>
    <label>Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Company_Avatar_URL__c.field-meta.xml
<CustomField>
    <fullName>Company_Avatar_URL__c</fullName>
    <description>Company Avatar picture URL</description>
    <inlineHelpText>Company Avatar picture URL</inlineHelpText>
    <label>Company Avatar URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Company_LinkedIn__c.field-meta.xml
<CustomField>
    <fullName>Company_LinkedIn__c</fullName>
    <inlineHelpText>Company LinkedIn Profile URL</inlineHelpText>
    <label>Company LinkedIn</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LinkedIn__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn__c</fullName>
    <description>LinkedIn Profile URL</description>
    <inlineHelpText>LinkedIn Profile URL</inlineHelpText>
    <label>LinkedIn</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Xing__c.field-meta.xml
<CustomField>
    <fullName>Xing__c</fullName>
    <description>Xing Profile URL</description>
    <inlineHelpText>Xing Profile URL</inlineHelpText>
    <label>Xing</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/CustomSettingsService.cls
/**
 * @description       : Custom Settings Service
 * @group             : CustomSettings
 * @last modified on  : 02-09-2022
 * @last modified by  : scarreira@ibs-technology.com
**/
public with sharing class CustomSettingsService {
	/**
	* @description Get custom field mapping wrapper object response
	* @author scarreira@ibs-technology.com | 01-31-2022 
	* @return Map<String, Object> 
	**/
	public static Map<String, Object> getCustomFieldMappingManager() {
		Map<String, Object> result = new Map<String, Object>();
		Map<String, Object> customFieldMapping = CustomSettingsService.getCustomFieldMapping();
		result.put('Results', customFieldMapping);
		result.put('Error', null);
		return result;
	}

    /**
    * @description generates a map of custom field mapping. The values are stored on hiearchal custom settings
	* and we retrieve the org level values.
	* we query the standard objects fields to see if the fields are accessible and updatable and if a field is not
	* it will not be returned
	*
    * @author ilya.litovchik@succraft.com | 01-27-2022 
    * @return Map<String, Object> 
    **/
    public static Map<String, Object> getCustomFieldMapping() {
        Map<String, SObjectField> accountFieldMap = Schema.Account.getSObjectType().getDescribe().fields.getMap();
        Map<String, SObjectField> leadFieldMap = Schema.Lead.getSObjectType().getDescribe().fields.getMap();
        Map<String, SObjectField> contactFieldMap = Schema.Contact.getSObjectType().getDescribe().fields.getMap();
        Map<String, Map<String, String>> data = new Map<String, Map<String, String>>{
			'Account' => new Map<String, String>(),
			'Contact' => new Map<String, String>(),
			'Lead' => new Map<String, String>()
        };

        Map<String, Object> settings = CustomFieldMapping__c.getInstance(UserInfo.getOrganizationId()).getPopulatedFieldsAsMap();

        for (String key : DEFAULT_VALUES.keySet()) {
            String settingValue = (String) settings.get(key);
            String value = String.isBlank(settingValue) ? DEFAULT_VALUES.get(key) : (String) settings.get(key);
            String objectKey = '';

            Map<String, SObjectField> sObjectFieldMap = new Map<String, SObjectField>();

            if (key.contains('Account_')) {
                sObjectFieldMap = accountFieldMap;
                objectKey = 'Account';
            } else if (key.contains('Lead_') || key.contains('Company_')) {
                sObjectFieldMap = leadFieldMap;
                objectKey = 'Lead';
            } else if (key.contains('Contact_')) {
                sObjectFieldMap = contactFieldMap;
                objectKey = 'Contact';
            }

            DescribeFieldResult fieldResult = sObjectFieldMap.containsKey(value) ? sObjectFieldMap.get(value).getDescribe() : null;

            if (fieldResult == null || !fieldResult.isAccessible() || !fieldResult.isUpdateable() || value == '-') {
                value = null;
            }

            Map<String, String> objectMap = data.get(objectKey);

            if (API_LABEL_MAPPING.containsKey(objectKey)) {
                if(API_LABEL_MAPPING.get(objectKey).containsKey(key)){
                    objectMap.put(API_LABEL_MAPPING.get(objectKey).get(key), value);
                }
            }
        }

        return data;
    }

	private static final String NAMESPACE = ''; // namespace with underscores (to use in scratch orgs without namespace)

	// Default field Values
    private static Map<String, String> DEFAULT_VALUES = new Map<String, String>{
		NAMESPACE + 'Account_Annual_Revenue__c' => 'AnnualRevenue',
		NAMESPACE + 'Account_Brand_Name__c' => NAMESPACE + 'Brand_Name__c',
		NAMESPACE + 'Account_DunsNumber__c' => '',
		NAMESPACE + 'Account_Industry__c' => 'Industry',
		NAMESPACE + 'Account_LinkedIn__c' => NAMESPACE + 'LinkedIn__c',
		NAMESPACE + 'Account_Number_Of_Employees__c' => 'NumberOfEmployees',
		NAMESPACE + 'Account_SIC__c' => 'Sic',
		NAMESPACE + 'Account_Website__c' => 'Website',
		NAMESPACE + 'Account_YearStarted__c' => '',
		NAMESPACE + 'Account_Avatar_URL__c' => NAMESPACE + 'avatar_url__c',
		NAMESPACE + 'Account_Billing_City__c' => 'BillingCity',
		NAMESPACE + 'Account_Billing_Country__c' => 'BillingCountry',
		NAMESPACE + 'Account_Billing_Country_Code__c' => 'BillingCountryCode',
		NAMESPACE + 'Account_Billing_Street__c' => 'BillingStreet',
		NAMESPACE + 'Account_Postal_Code__c' => 'BillingPostalCode',
		NAMESPACE + 'Account_Billing_State__c' => 'BillingState',
		NAMESPACE + 'Account_Description__c' => 'Description',
		NAMESPACE + 'Account_Phone__c' => 'Phone',
		NAMESPACE + 'Account_HitHorizons_ID__c' => NAMESPACE + 'HitHorizonsID__c',
		NAMESPACE + 'Lead_Annual_Revenue__c' => 'AnnualRevenue',
		NAMESPACE + 'Lead_Brand_Name__c' => NAMESPACE + 'Brand_Name__c',
		NAMESPACE + 'Lead_DunsNumber__c' => '',
		NAMESPACE + 'Lead_Industry__c' => 'Industry',
		NAMESPACE + 'Lead_LinkedIn__c' => NAMESPACE + 'LinkedIn__c',
		NAMESPACE + 'Lead_Number_Of_Employees__c' => 'NumberOfEmployees',
		NAMESPACE + 'Lead_SIC__c' => '',
		NAMESPACE + 'Lead_Website__c' => 'Website',
		NAMESPACE + 'Lead_YearStarted__c' => '',
		NAMESPACE + 'Lead_Xing__c' => NAMESPACE + 'Xing__c',
		NAMESPACE + 'Lead_Avatar_URL__c' => NAMESPACE + 'avatar_url__c',
		NAMESPACE + 'Company_Avatar_URL__c' => NAMESPACE + 'Company_Avatar_URL__c',
		NAMESPACE + 'Company_LinkedIn__c' => NAMESPACE + 'Company_LinkedIn__c',
		NAMESPACE + 'Lead_City__c' => 'City',
		NAMESPACE + 'Lead_Country__c' => 'Country',
		NAMESPACE + 'Lead_Country_Code__c' => 'CountryCode',
		NAMESPACE + 'Lead_Billing_Street__c' => 'Street',
		NAMESPACE + 'Lead_Postal_Code__c' => 'PostalCode',
		NAMESPACE + 'Lead_Billing_State__c' => 'State',
		NAMESPACE + 'Lead_Description__c' => 'Description',
		NAMESPACE + 'Lead_Title__c' => 'Title',
		NAMESPACE + 'Lead_Phone__c' => 'Phone',
		NAMESPACE + 'Lead_Salutation__c' => 'Salutation',
		NAMESPACE + 'Lead_HitHorizons_ID__c' => NAMESPACE + 'HitHorizonsID__c',
		NAMESPACE + 'Contact_LinkedIn__c' => NAMESPACE + 'LinkedIn__c',
		NAMESPACE + 'Contact_Xing__c' => NAMESPACE + 'Xing__c',
		NAMESPACE + 'Contact_Avatar_URL__c' => NAMESPACE + 'avatar_url__c',
		NAMESPACE + 'Contact_Title__c' => 'Title',
		NAMESPACE + 'Contact_Phone__c' => 'Phone',
		NAMESPACE + 'Contact_Salutation__c' => 'Salutation'
    };
	
    private static Map<String, Map<String, String>> API_LABEL_MAPPING = new Map<String, Map<String, String>>{
		'Account' => new Map<String, String>{
				NAMESPACE + 'Account_Annual_Revenue__c' => 'AnnualRevenue',
				NAMESPACE + 'Account_Brand_Name__c' => 'BrandName',
				NAMESPACE + 'Account_DunsNumber__c' => 'DunsNumber',
				NAMESPACE + 'Account_Industry__c' => 'Industry',
				NAMESPACE + 'Account_LinkedIn__c' => 'LinkedIn',
				NAMESPACE + 'Account_Number_Of_Employees__c' => 'NumberOfEmployees',
				NAMESPACE + 'Account_SIC__c' => 'Sic',
				NAMESPACE + 'Account_Website__c' => 'Website',
				NAMESPACE + 'Account_YearStarted__c' => 'YearStarted',
				NAMESPACE + 'Account_Avatar_URL__c' => 'AvatarURL',
				NAMESPACE + 'Account_Billing_City__c' => 'City',
				NAMESPACE + 'Account_Billing_Country__c' => 'Country',
				NAMESPACE + 'Account_Billing_Country_Code__c' => 'CountryCode',
				NAMESPACE + 'Account_Billing_Street__c' => 'Street',
				NAMESPACE + 'Account_Postal_Code__c' => 'PostalCode',
				NAMESPACE + 'Account_Billing_State__c' => 'State',
				NAMESPACE + 'Account_Description__c' => 'Description',
				NAMESPACE + 'Account_Phone__c' => 'Phone',
				NAMESPACE + 'Account_HitHorizons_ID__c' => 'HitHorizonsID'
		},
		'Lead' => new Map<String, String>{
				NAMESPACE + 'Lead_Annual_Revenue__c' => 'AnnualRevenue',
				NAMESPACE + 'Lead_Brand_Name__c' => 'BrandName',
				NAMESPACE + 'Lead_DunsNumber__c' => 'CompanyDunsNumber',
				NAMESPACE + 'Lead_Industry__c' => 'Industry',
				NAMESPACE + 'Lead_LinkedIn__c' => 'LinkedIn',
				NAMESPACE + 'Lead_Number_Of_Employees__c' => 'NumberOfEmployees',
				NAMESPACE + 'Lead_SIC__c' => 'Sic',
				NAMESPACE + 'Lead_Website__c' => 'Website',
				NAMESPACE + 'Lead_YearStarted__c' => 'YearStarted',
				NAMESPACE + 'Lead_Xing__c' => 'Xing',
				NAMESPACE + 'Lead_Avatar_URL__c' => 'AvatarURL',
				NAMESPACE + 'Company_Avatar_URL__c' => 'CompanyAvatarURL',
				NAMESPACE + 'Company_LinkedIn__c' => 'CompanyLinkedIn',
				NAMESPACE + 'Lead_City__c' => 'City',
				NAMESPACE + 'Lead_Country__c' => 'Country',
				NAMESPACE + 'Lead_Country_Code__c' => 'CountryCode',
				NAMESPACE + 'Lead_Billing_Street__c' => 'Street',
				NAMESPACE + 'Lead_Postal_Code__c' => 'PostalCode',
				NAMESPACE + 'Lead_Billing_State__c' => 'State',
				NAMESPACE + 'Lead_Description__c' => 'Description',
				NAMESPACE + 'Lead_Title__c' => 'Title',
				NAMESPACE + 'Lead_Phone__c' => 'Phone',
				NAMESPACE + 'Lead_Salutation__c' => 'Salutation',
				NAMESPACE + 'Lead_HitHorizons_ID__c' => 'HitHorizonsID'
		},
		'Contact' => new Map<String, String>{
				NAMESPACE + 'Contact_LinkedIn__c' => 'LinkedIn',
				NAMESPACE + 'Contact_Xing__c' => 'Xing',
				NAMESPACE + 'Contact_Avatar_URL__c' => 'AvatarURL',
				NAMESPACE + 'Contact_Title__c' => 'Title',
				NAMESPACE + 'Contact_Phone__c' => 'Phone',
				NAMESPACE + 'Contact_Salutation__c' => 'Salutation'
		}
    };
}